package com.example.demo.domain;

import java.util.ArrayList;
import java.util.List;

public class AuthorityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public AuthorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdEqualTo(Integer value) {
            addCriterion("department_id =", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotEqualTo(Integer value) {
            addCriterion("department_id <>", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThan(Integer value) {
            addCriterion("department_id >", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("department_id >=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThan(Integer value) {
            addCriterion("department_id <", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("department_id <=", value, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdIn(List<Integer> values) {
            addCriterion("department_id in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotIn(List<Integer> values) {
            addCriterion("department_id not in", values, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdBetween(Integer value1, Integer value2) {
            addCriterion("department_id between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andDepartmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("department_id not between", value1, value2, "departmentId");
            return (Criteria) this;
        }

        public Criteria andFlieIdIsNull() {
            addCriterion("flie_id is null");
            return (Criteria) this;
        }

        public Criteria andFlieIdIsNotNull() {
            addCriterion("flie_id is not null");
            return (Criteria) this;
        }

        public Criteria andFlieIdEqualTo(Integer value) {
            addCriterion("flie_id =", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdNotEqualTo(Integer value) {
            addCriterion("flie_id <>", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdGreaterThan(Integer value) {
            addCriterion("flie_id >", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("flie_id >=", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdLessThan(Integer value) {
            addCriterion("flie_id <", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdLessThanOrEqualTo(Integer value) {
            addCriterion("flie_id <=", value, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdIn(List<Integer> values) {
            addCriterion("flie_id in", values, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdNotIn(List<Integer> values) {
            addCriterion("flie_id not in", values, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdBetween(Integer value1, Integer value2) {
            addCriterion("flie_id between", value1, value2, "flieId");
            return (Criteria) this;
        }

        public Criteria andFlieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("flie_id not between", value1, value2, "flieId");
            return (Criteria) this;
        }

        public Criteria andReadIsNull() {
            addCriterion("read is null");
            return (Criteria) this;
        }

        public Criteria andReadIsNotNull() {
            addCriterion("read is not null");
            return (Criteria) this;
        }

        public Criteria andReadEqualTo(Integer value) {
            addCriterion("read =", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotEqualTo(Integer value) {
            addCriterion("read <>", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadGreaterThan(Integer value) {
            addCriterion("read >", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadGreaterThanOrEqualTo(Integer value) {
            addCriterion("read >=", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadLessThan(Integer value) {
            addCriterion("read <", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadLessThanOrEqualTo(Integer value) {
            addCriterion("read <=", value, "read");
            return (Criteria) this;
        }

        public Criteria andReadIn(List<Integer> values) {
            addCriterion("read in", values, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotIn(List<Integer> values) {
            addCriterion("read not in", values, "read");
            return (Criteria) this;
        }

        public Criteria andReadBetween(Integer value1, Integer value2) {
            addCriterion("read between", value1, value2, "read");
            return (Criteria) this;
        }

        public Criteria andReadNotBetween(Integer value1, Integer value2) {
            addCriterion("read not between", value1, value2, "read");
            return (Criteria) this;
        }

        public Criteria andDownloadIsNull() {
            addCriterion("download is null");
            return (Criteria) this;
        }

        public Criteria andDownloadIsNotNull() {
            addCriterion("download is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadEqualTo(Integer value) {
            addCriterion("download =", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadNotEqualTo(Integer value) {
            addCriterion("download <>", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadGreaterThan(Integer value) {
            addCriterion("download >", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadGreaterThanOrEqualTo(Integer value) {
            addCriterion("download >=", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadLessThan(Integer value) {
            addCriterion("download <", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadLessThanOrEqualTo(Integer value) {
            addCriterion("download <=", value, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadIn(List<Integer> values) {
            addCriterion("download in", values, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadNotIn(List<Integer> values) {
            addCriterion("download not in", values, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadBetween(Integer value1, Integer value2) {
            addCriterion("download between", value1, value2, "download");
            return (Criteria) this;
        }

        public Criteria andDownloadNotBetween(Integer value1, Integer value2) {
            addCriterion("download not between", value1, value2, "download");
            return (Criteria) this;
        }

        public Criteria andDeleteIsNull() {
            addCriterion("delete is null");
            return (Criteria) this;
        }

        public Criteria andDeleteIsNotNull() {
            addCriterion("delete is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteEqualTo(Integer value) {
            addCriterion("delete =", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotEqualTo(Integer value) {
            addCriterion("delete <>", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteGreaterThan(Integer value) {
            addCriterion("delete >", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete >=", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteLessThan(Integer value) {
            addCriterion("delete <", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("delete <=", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteIn(List<Integer> values) {
            addCriterion("delete in", values, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotIn(List<Integer> values) {
            addCriterion("delete not in", values, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteBetween(Integer value1, Integer value2) {
            addCriterion("delete between", value1, value2, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("delete not between", value1, value2, "delete");
            return (Criteria) this;
        }

        public Criteria andChangeNameIsNull() {
            addCriterion("change_name is null");
            return (Criteria) this;
        }

        public Criteria andChangeNameIsNotNull() {
            addCriterion("change_name is not null");
            return (Criteria) this;
        }

        public Criteria andChangeNameEqualTo(Integer value) {
            addCriterion("change_name =", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameNotEqualTo(Integer value) {
            addCriterion("change_name <>", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameGreaterThan(Integer value) {
            addCriterion("change_name >", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameGreaterThanOrEqualTo(Integer value) {
            addCriterion("change_name >=", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameLessThan(Integer value) {
            addCriterion("change_name <", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameLessThanOrEqualTo(Integer value) {
            addCriterion("change_name <=", value, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameIn(List<Integer> values) {
            addCriterion("change_name in", values, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameNotIn(List<Integer> values) {
            addCriterion("change_name not in", values, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameBetween(Integer value1, Integer value2) {
            addCriterion("change_name between", value1, value2, "changeName");
            return (Criteria) this;
        }

        public Criteria andChangeNameNotBetween(Integer value1, Integer value2) {
            addCriterion("change_name not between", value1, value2, "changeName");
            return (Criteria) this;
        }

        public Criteria andShareIsNull() {
            addCriterion("share is null");
            return (Criteria) this;
        }

        public Criteria andShareIsNotNull() {
            addCriterion("share is not null");
            return (Criteria) this;
        }

        public Criteria andShareEqualTo(Integer value) {
            addCriterion("share =", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareNotEqualTo(Integer value) {
            addCriterion("share <>", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareGreaterThan(Integer value) {
            addCriterion("share >", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareGreaterThanOrEqualTo(Integer value) {
            addCriterion("share >=", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareLessThan(Integer value) {
            addCriterion("share <", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareLessThanOrEqualTo(Integer value) {
            addCriterion("share <=", value, "share");
            return (Criteria) this;
        }

        public Criteria andShareIn(List<Integer> values) {
            addCriterion("share in", values, "share");
            return (Criteria) this;
        }

        public Criteria andShareNotIn(List<Integer> values) {
            addCriterion("share not in", values, "share");
            return (Criteria) this;
        }

        public Criteria andShareBetween(Integer value1, Integer value2) {
            addCriterion("share between", value1, value2, "share");
            return (Criteria) this;
        }

        public Criteria andShareNotBetween(Integer value1, Integer value2) {
            addCriterion("share not between", value1, value2, "share");
            return (Criteria) this;
        }

        public Criteria andCreateDirIsNull() {
            addCriterion("create_dir is null");
            return (Criteria) this;
        }

        public Criteria andCreateDirIsNotNull() {
            addCriterion("create_dir is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDirEqualTo(Integer value) {
            addCriterion("create_dir =", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirNotEqualTo(Integer value) {
            addCriterion("create_dir <>", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirGreaterThan(Integer value) {
            addCriterion("create_dir >", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_dir >=", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirLessThan(Integer value) {
            addCriterion("create_dir <", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirLessThanOrEqualTo(Integer value) {
            addCriterion("create_dir <=", value, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirIn(List<Integer> values) {
            addCriterion("create_dir in", values, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirNotIn(List<Integer> values) {
            addCriterion("create_dir not in", values, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirBetween(Integer value1, Integer value2) {
            addCriterion("create_dir between", value1, value2, "createDir");
            return (Criteria) this;
        }

        public Criteria andCreateDirNotBetween(Integer value1, Integer value2) {
            addCriterion("create_dir not between", value1, value2, "createDir");
            return (Criteria) this;
        }

        public Criteria andUploadIsNull() {
            addCriterion("upload is null");
            return (Criteria) this;
        }

        public Criteria andUploadIsNotNull() {
            addCriterion("upload is not null");
            return (Criteria) this;
        }

        public Criteria andUploadEqualTo(Integer value) {
            addCriterion("upload =", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadNotEqualTo(Integer value) {
            addCriterion("upload <>", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadGreaterThan(Integer value) {
            addCriterion("upload >", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadGreaterThanOrEqualTo(Integer value) {
            addCriterion("upload >=", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadLessThan(Integer value) {
            addCriterion("upload <", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadLessThanOrEqualTo(Integer value) {
            addCriterion("upload <=", value, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadIn(List<Integer> values) {
            addCriterion("upload in", values, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadNotIn(List<Integer> values) {
            addCriterion("upload not in", values, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadBetween(Integer value1, Integer value2) {
            addCriterion("upload between", value1, value2, "upload");
            return (Criteria) this;
        }

        public Criteria andUploadNotBetween(Integer value1, Integer value2) {
            addCriterion("upload not between", value1, value2, "upload");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 29 21:11:36 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}