package com.example.demo.domain;

import java.io.Serializable;

public class Authority implements Serializable {
	
	
	public Authority() {}
    public Authority(Integer departmentId, Integer flieId) {
		
		this.departmentId = departmentId;
		this.flieId = flieId;
		this.read = 0;
		this.changeName = 0;
		this.delete = 0;
		this.download = 0;
		this.update = 0;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.department_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.flie_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer flieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.read
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.update
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer update;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.download
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.delete
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.change_name
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private Integer changeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.department_id
     *
     * @return the value of authority.department_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.department_id
     *
     * @param departmentId the value for authority.department_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.flie_id
     *
     * @return the value of authority.flie_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getFlieId() {
        return flieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.flie_id
     *
     * @param flieId the value for authority.flie_id
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setFlieId(Integer flieId) {
        this.flieId = flieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.read
     *
     * @return the value of authority.read
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.read
     *
     * @param read the value for authority.read
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.update
     *
     * @return the value of authority.update
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.update
     *
     * @param update the value for authority.update
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setUpdate(Integer update) {
        this.update = update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.download
     *
     * @return the value of authority.download
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.download
     *
     * @param download the value for authority.download
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setDownload(Integer download) {
        this.download = download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.delete
     *
     * @return the value of authority.delete
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.delete
     *
     * @param delete the value for authority.delete
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.change_name
     *
     * @return the value of authority.change_name
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public Integer getChangeName() {
        return changeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.change_name
     *
     * @param changeName the value for authority.change_name
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    public void setChangeName(Integer changeName) {
        this.changeName = changeName;
    }
}