package com.example.demo.domain;

import java.io.Serializable;
import java.util.UUID;

import com.example.demo.enums.AuthorityType;
import com.example.demo.enums.StatusCode;
import com.example.demo.exception.PanException;

public class Authority implements Serializable {
	
	public Authority() {
		
	}
	
    public Authority(Integer departmentId, Integer flieId) {
    	this();
    	this.read = AuthorityType.UNAUTHORIZED.value();
		this.changeName = AuthorityType.UNAUTHORIZED.value();
		this.delete = AuthorityType.UNAUTHORIZED.value();
		this.download = AuthorityType.UNAUTHORIZED.value();
		this.createDir = AuthorityType.UNAUTHORIZED.value();
		this.share = AuthorityType.UNAUTHORIZED.value();
		this.upload = AuthorityType.UNAUTHORIZED.value();
		this.departmentId = departmentId;
		this.flieId = flieId;
		
	}
   
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.department_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.flie_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer flieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.read
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.download
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.delete
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.change_name
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer changeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.share
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer share;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_dir
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer createDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.upload
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private Integer upload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    private static final long serialVersionUID = 1L;
    
    
    private Integer isDelete = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.department_id
     *
     * @return the value of authority.department_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.department_id
     *
     * @param departmentId the value for authority.department_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.flie_id
     *
     * @return the value of authority.flie_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getFlieId() {
        return flieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.flie_id
     *
     * @param flieId the value for authority.flie_id
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setFlieId(Integer flieId) {
        this.flieId = flieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.read
     *
     * @return the value of authority.read
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.read
     *
     * @param read the value for authority.read
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setRead(Integer read) {
    	read = read == null ? 0 : read;
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.download
     *
     * @return the value of authority.download
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.download
     *
     * @param download the value for authority.download
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setDownload(Integer download) {
    	download = download == null ? 0 : download;
        this.download = download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.delete
     *
     * @return the value of authority.delete
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.delete
     *
     * @param delete the value for authority.delete
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setDelete(Integer delete) {
    	delete = delete == null ? 0 : delete;
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.change_name
     *
     * @return the value of authority.change_name
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getChangeName() {
        return changeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.change_name
     *
     * @param changeName the value for authority.change_name
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setChangeName(Integer changeName) {
    	changeName = changeName == null ? 0 : changeName;
        this.changeName = changeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.share
     *
     * @return the value of authority.share
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.share
     *
     * @param share the value for authority.share
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setShare(Integer share) {
    	share = share == null ? 0 : share;
        this.share = share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_dir
     *
     * @return the value of authority.create_dir
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getCreateDir() {
        return createDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_dir
     *
     * @param createDir the value for authority.create_dir
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setCreateDir(Integer createDir) {
    	createDir = createDir == null ? 0 : createDir;
        this.createDir = createDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.upload
     *
     * @return the value of authority.upload
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public Integer getUpload() {
        return upload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.upload
     *
     * @param upload the value for authority.upload
     *
     * @mbggenerated Tue Sep 29 21:11:36 CST 2020
     */
    public void setUpload(Integer upload) {
    	upload = upload == null ? 0 : upload;
        this.upload = upload;
    }
    
    
    public Integer getIsDelete(){
    	return isDelete;
    }    
    
    public void setIsDelete(Integer isDelete) {
    	this.isDelete = isDelete;
    }
    
 

	/**
     * 
     * @Title getAuthByType
     * @Description 获取指定的权限信息
     * @param authorityType 权限枚举类型
     * @return 返回指定的权限，1代表有权限，0代表无权限
     * @throws PanException
     */
    public Integer getAuthByType(AuthorityType authorityType) {
    	switch(authorityType) {
    	case READ:
    		return getRead();
    	case CREATE_DIR:
    		return getCreateDir();
    	case UPLOAD:
    		return getUpload();
    	case DELETE:
    		return getDelete();
    	case DOWNLOAD:
    		return getDownload();
    	case SHARE:
    		return getShare();
    	case RENAME:
    		return getChangeName();
    	default:
    		throw new PanException(StatusCode.AUTHORITY_IS_NOT_EXISTED.code(), StatusCode.AUTHORITY_IS_NOT_EXISTED.message());	
    	}
    }
    
    

	@Override
	public String toString() {
		return "Authority [id=" + id + ", departmentId=" + departmentId + ", flieId=" + flieId + ", read=" + read
				+ ", download=" + download + ", delete=" + delete + ", changeName=" + changeName + ", share=" + share
				+ ", createDir=" + createDir + ", upload=" + upload + "]";
	}
    
    
    
}