package com.example.demo.mapper;

import com.example.demo.domain.Authority;
import com.example.demo.domain.AuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    Authority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Fri Sep 18 18:15:09 CST 2020
     */
    int updateByPrimaryKey(Authority record);
    
    boolean batchInsert(List<Authority> authoritys);
    
    boolean batchDelete(List<Integer> authorityIds);
    
    List<Authority> getByFileId(Integer fileId);
    
    Authority getByFileIdAndDepartmentId(@Param("fileId")Integer fileId, @Param("departmentId")Integer departmentId);
}